// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Calls provides a mock function with given fields:
func (_m *Client) Calls() Caller {
	ret := _m.Called()

	var r0 Caller
	if rf, ok := ret.Get(0).(func() Caller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Caller)
		}
	}

	return r0
}

// Messages provides a mock function with given fields:
func (_m *Client) Messages() Sender {
	ret := _m.Called()

	var r0 Sender
	if rf, ok := ret.Get(0).(func() Sender); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Sender)
		}
	}

	return r0
}
