// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// buildRouter provides a mock function with given fields:
func (_m *Config) buildRouter() Router {
	ret := _m.Called()

	var r0 Router
	if rf, ok := ret.Get(0).(func() Router); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Router)
		}
	}

	return r0
}
