name: CI

env:
  REGISTRY: "docker.pkg.github.com"
  ORG: "jonathanwthom"
  IMAGE_NAME: "meminders"

on:
  push:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.1

    - name: Test
      run: go test -v ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs: lint_and_test

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t jonathanwthom/meminders/meminders .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jonathanwthom/meminders/meminders
          tag_with_ref: false

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,DATABASE_URL,GITHUB_ACTOR,GITHUB_TOKEN
          script: |
            docker login -u $GITHUB_ACTOR -p $GITHUB_TOKEN docker.pkg.github.com

            # Stop running container
            docker stop $(echo $IMAGE_NAME)

            # Remove old container
            docker rm $(echo $IMAGE_NAME)

            # Run a new container from a new image
            docker run -d \
            --restart always \
            --env-file .env.production \
            --name $(echo $IMAGE_NAME) \
            -v $(pwd)/$(echo $DATABASE_URL):/app/$(echo $DATABASE_URL) \
            -v $(pwd)/.env.production:/app/.env.production \
            docker.pkg.github.com/jonathanwthom/meminders/meminders
